module C2FFI4RB
  class Parser
    @struct_type: untyped

    @anon_counter: Integer

    TYPE_TABLE: Hash[String, String]

    def self.parse: (untyped arr) -> untyped

    def initialize: () -> void

    def parse: (untyped arr) -> String?

    private

    def parse_toplevel: (untyped form) -> String?

    def add_struct: (untyped name) -> String?

    def add_enum: (untyped name) -> String

    def make_struct: (untyped form) -> String

    def parse_type: (untyped form) -> untyped
  end
end
