#!/usr/bin/env ruby
# frozen_string_literal: true

## This is meant to be more of an unsophisticated demo than a
## production tool.  Generating spec and ruby files should be part of
## your build system.  But this is how you can use it.

require 'optparse'
require 'c2ffi4rb'

type_table = {}

opts = OptionParser.new
opts.banner = 'Usage: c2ffi4rb [options] [file1, file2, ...]'
opts.on('-t FILE', '--table FILE', 'Type conversion table TSV') do |file|
  File.open(file) do |io|
    io.each_line do |line|
      next if line =~ /^#/

      from, to = line.chomp.split("\t")
      type_table[from] = to
    end
  end
end
opts.on('-h', '--help', 'Show this message') do
  puts opts
  exit
end
opts.on('-v', '--version', 'Show version') do
  puts C2FFI4RB::VERSION
  exit
end
opts.parse!

if ARGV.empty? && $stdin.tty?
  warn opts
  exit 1
end

spec = []
ARGV.each do |file|
  File.open(file) do |io|
    spec += JSON.parse(io.read, Hash[:symbolize_names, true])
  end
end

spec += JSON.parse($stdin.read, Hash[:symbolize_names, true]) unless $stdin.tty?

C2FFI4RB::BindGen.new(type_table).generate_bindings(spec)
