#!/usr/bin/env ruby
# frozen_string_literal: true

## This is meant to be more of an unsophisticated demo than a
## production tool.  Generating spec and ruby files should be part of
## your build system.  But this is how you can use it.

require 'optparse'
require 'c2ffi4rb'

Version = C2FFI4RB::VERSION # Fixme

opts = OptionParser.new
opts.banner = 'Usage: c2ffi4rb [options] [file1, file2, ...]'
opts.on('-h', '--help', 'Show this message') do
  puts opts
  exit
end
opts.parse!

if ARGV.empty?
  warn opts
  exit 1
end

spec = []
ARGV.each do |file|
  File.open(file) do |io|
    spec += JSON.parse(io.read, Hash[:symbolize_names, true])
  end
end

C2FFI4RB::BindGen.generate_bindings(spec)
