name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
        ruby: ["3.3"]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build c2ffi
        run: |
          sudo apt-get install -y clang-16 llvm-16-dev libclang-16-dev libcurl4-gnutls-dev libcairo2-dev
          clang --version
          wget https://github.com/rpav/c2ffi/archive/refs/heads/llvm-16.0.0.zip
          unzip llvm-16.0.0.zip
          cd c2ffi-llvm-16.0.0 && mkdir build && cd build && cmake .. && make -j$(nproc)
      - name: Run tests
        run: bundle exec rake test
        env:
          C2FFI: ${{ github.workspace }}/c2ffi-llvm-16.0.0/build/bin/c2ffi
